version: 2

models:
  - name: switches
    description: "This table contains details about switches."
    columns:
      - name: switch_id
        description: "Unique identifier for a switch."
        tests:
          - unique
          - not_null
      - name: switch_name
        description: "Name of the switch."
        tests:
          - not_null
      - name: manufacturer
        description: "Switch manufacturer."
        tests:
          - not_null
      - name: spring_force
        description: "Switch spring force."
        tests:
          - not_null
      - name: stem_type
        description: "Switch stem type."
        tests:
          - not_null
      - name: stem_material
        description: "Switch stem material."
        tests:
          - not_null
      - name: top_housing
        description: "Switch top housing material."
        tests:
          - not_null
      - name: bottom_housing
        description: "Switch bottom housing material."
        tests:
          - not_null
      - name: own_status
        description: "Switch ownership."
        tests:
          - not_null
      - name: rating
        description: "Rating for the switch."
        tests:
          - not_null

  - name: keyboards
    description: "This table contains details about keyboards."
    columns:
      - name: keyboard_id
        description: "Unique identifier for a keyboard."
        tests:
          - unique
          - not_null
      - name: keyboard_name
        description: "Name of the keyboard."
        tests:
          - not_null
      - name: brand
        description: "Keyboard's brand."
        tests:
          - not_null
      - name: keyboard_size
        description: "Size of the keyboard."
        tests:
          - not_null
      - name: plate
        description: "Keyboard plate material ."
        tests:
          - not_null
      - name: weight_material
        description: "Keyboard weight material."
        tests:
          - not_null

  - name: switch_ratings
    description: "Aggregate ratings for switch characteristics."
    columns:
      - name: switch_name
        description: "Name of switch."
        tests:
          - not_null
      - name: spring_force
        description: "Switch spring force."
        tests:
          - not_null
      - name: stem_type
        description: "Switch stem type."
        tests:
          - not_null
      - name: stem_material
        description: "Switch stem material."
        tests:
          - not_null
      - name: top_housing
        description: "Switch top housing material."
        tests:
          - not_null
      - name: bottom_housing
        description: "Switch bottom housing material."
        tests:
          - not_null
      - name: avg_rating
        description: "Average rating for the combination of switch characteristics."
        tests:
          - not_null

  - name: best_rated_switch_characteristics
    description: "Best-rated switch characteristics."
    columns:
      - name: switch_name
        description: "Name of switch."
        tests:
          - not_null
      - name: spring_force
        description: "Switch spring force."
        tests:
          - not_null
      - name: stem_type
        description: "Switch stem type."
        tests:
          - not_null
      - name: stem_material
        description: "Switch stem material."
        tests:
          - not_null
      - name: top_housing
        description: "Switch top housing material."
        tests:
          - not_null
      - name: bottom_housing
        description: "Switch bottom housing material."
        tests:
          - not_null
      - name: avg_rating
        description: "Average rating for the combination of switch characteristics."
        tests:
          - not_null

  - name: potential_next_switch_purchase
    description: "Potential next switch purchase based on best-rated characteristics."
    columns:
      - name: switch_id
        description: "Unique identifier for a switch."
        tests:
          - unique
          - not_null
      - name: switch_name
        description: "Name of the switch."
        tests:
          - not_null
      - name: manufacturer
        description: "Switch manufacturer."
        tests:
          - not_null
      - name: spring_force
        description: "Switch spring force."
        tests:
          - not_null
      - name: stem_type
        description: "Switch stem type"
        tests:
          - not_null
      - name: stem_material
        description: "Switch stem material."
        tests:
          - not_null
      - name: top_housing
        description: "Switch top housing material."
        tests:
          - not_null
      - name: bottom_housing
        description: "Switch bottom housing material."
        tests:
          - not_null
      - name: rating
        description: "Rating for the switch."
        tests:
          - not_null
      - name: own_status
        description: "Switch ownership."
        tests:
          - not_null