CREATE TABLE switches (
    switch_id SERIAL PRIMARY KEY,
    switch_name VARCHAR(40),
    manufacturer VARCHAR(15),
    spring_force INTEGER NOT NULL,
    stem_type VARCHAR(10),
    stem_material VARCHAR(20),
    top_housing VARCHAR(20),
    bottom_housing VARCHAR(20),
    own_status BOOLEAN NOT NULL,
    rating DECIMAL(2,1) CHECK (rating >= 1 AND rating <= 10)
);

INSERT INTO switches (switch_name, manufacturer, spring_force, stem_type, stem_material, top_housing, bottom_housing, own_status, rating) VALUES
('Baby Raccoon', 'Gateron', 63, 'Regular', 'POM', 'Polycarbonate', 'PA66', FALSE, NULL),
('Summertime', 'Gateron', 63, 'Long', 'Ink', 'Milky Plastic', 'Milky Plastic', FALSE, NULL),
('Mountain-Top', 'Gateron', 50, 'Regular', 'POM', 'Nylon', 'Nylon', FALSE, NULL),
('UHMknown', 'Gateron', 57, 'Regular', 'UHMWPE', 'Nylon', 'INK V2 Plastic', FALSE, NULL),
('Jingles', 'JWK', 52, 'Long', 'P3', 'Nylon', 'POM', FALSE, NULL),
('Cream+', 'Kalih', 63.5, 'Long', 'POM', 'POM', 'POM', FALSE, NULL),
('Medium', 'Tecsee', 63.5, 'Regular', 'POM', 'HPE', 'Polycarbonate', FALSE, NULL),
('Honeydew', 'Tecsee', 65, 'Regular', 'POM', 'HPE', 'HPE', FALSE, NULL),
('Lychee Milk', 'Tecsee', 68, 'Regular', 'UHMWPE', 'Nylon', 'Nylon', FALSE, NULL),
('Sunny Side Up', 'Tecsee', 63.5, 'Regular', 'POM', 'HPE', 'HPE', FALSE, NULL),
('SW Vintage', 'Tecsee', 63.5, 'Regular', 'POM', 'Nylon', 'Nylon', FALSE, NULL),
('SW Popcorn', 'BSUN', 58, 'Regular', 'LY', 'LY', 'LY', FALSE, NULL),
('Milk Tea Siam', 'BSUN', 44, 'Regular', 'LY', 'POM', 'POM', FALSE, NULL),
('Sunset Yellow', 'BSUN', 52, 'Regular', 'UPE', 'POM', 'POM', FALSE, NULL),
('Latte', 'Owlab', 58, 'Long', 'POM', 'POK', 'Nylon', FALSE, NULL),
('Otos', 'Owlab', 58, 'Long', 'POM', 'Nylon', 'Nylon', FALSE, NULL),
('Muguet Rose', 'Keygeek', 48, 'Regular', 'U2', 'Polycarbonate', 'Polycarbonate', FALSE, NULL),
('Luxury', 'Keygeek', 63.5, 'Regular', 'L2', 'U2', 'PA66', FALSE, NULL),
('Iced Latte', 'DK Roastery', 55, 'Regular', 'POM', 'Polycarbonate', 'Polycarbonate', FALSE, NULL),
('Durian Ice Cream', 'Lichicx', 42, 'Regular', 'POM', 'Nylon', 'Nylon', FALSE, NULL),
('Pine', 'Loobed', 61, 'Regular', 'POM', 'POM', 'POM', FALSE, NULL),
('Little Daisy', 'Emotoys', 65, 'Regular', 'Nylon', 'Polycarbonate', 'Polycarbonate', FALSE, NULL),
('Diamond', 'Avalon', 58, 'Regular', 'POM', 'Nylon', 'Nylon', FALSE, NULL),
('Oil King', 'Gateron', 55, 'Regular', 'POM', 'Nylon', 'INK V2 Plastic', TRUE, 8.5),
('SW Pure Berry', 'Gateron', 62, 'Long', 'POM', 'Polycarbonate', 'Polycarbonate', TRUE, 8),
('Milky Clear', 'Gateron', 40, 'Regular', 'POM', 'Nylon', 'Nylon', TRUE, 8),
('Black Ink V2', 'Gateron', 70, 'Regular', 'POM', 'INK V2 Plastic', 'INK V2 Plastic', TRUE, 8),
('Cream Soda', 'Gateron', 63, 'Long', 'POM', 'Milky Plastic', 'INK V2 Plastic', TRUE, 7.5),
('Box Ink V2', 'Gateron', 60, 'Regular', 'POM', 'Polycarbonate', 'Polycarbonate', TRUE, 7),
('SW Modern Gray', 'Gateron', 62, 'Long', 'POM', 'Polycarbonate', 'Polycarbonate', TRUE, 7),
('CM', 'Gateron', 63.5, 'Regular', 'POM', 'PA66', 'PA66', TRUE, 6),
('XEF Curry', 'Gateron', 60, 'Regular', 'POM', 'Polycarbonate', 'Nylon', TRUE, 5),
('Ms. Piggy', 'JWK', 62, 'Regular', 'POM', 'Nylon', 'Nylon', TRUE, 8.5),
('FFF', 'JWK', 62, 'Regular', 'POM', 'Polycarbonate', 'Polycarbonate', TRUE, 7.5),
('Autumn Rain', 'JWK', 63.5, 'Long', 'P3', 'Nylon', 'Nylon', TRUE, 7),
('Alpaca', 'JWK', 62, 'Regular', 'POM', 'Polycarbonate', 'Nylon', TRUE, 7),
('Seal', 'JWK', 78, 'Regular', 'POM', 'Polycarbonate', 'Nylon', TRUE, 4),
('Lavender', 'Durock', 65, 'Regular', 'POM', 'Nylon', 'Nylon', TRUE, 7),
('Korbs', 'Durock', 62, 'Regular', 'POM', 'Nylon', 'Nylon', TRUE, 7),
('Mekanisk Ultramarine', 'Durock', 65, 'Regular', 'P3', 'Nylon', 'Polyamide', TRUE, 6.5),
('Ice Mint', 'FLCMMK', 50, 'Regular', 'POM', 'POM', 'POM', TRUE, 8),
('NK CREAM Launch', 'Kailh', 63.5, 'Long', 'POM', 'POM', 'POM', TRUE, 6.5),
('NK CREAM Dream', 'Kailh', 70, 'Regular', 'POM', 'POM', 'POM', TRUE, 5),
('S1-Peaches', 'Tecsee', 63.5, 'Long', 'POM', 'HPE', 'HPE', TRUE, 8),
('Zaku', 'Tecsee', 63.5, 'Long', 'POM', 'Polycarbonate', 'Nylon', TRUE, 7.5),
('Panghu Giant V5', 'Tecsee', 63.5, 'Regular', 'UHMWPE', 'UHMWPE', 'Nylon', TRUE, 5),
('Sarokeys x Geon BCP', 'BSUN', 57, 'Regular', 'POM', 'Nylon', 'Nylon', TRUE, 8.5),
('Meteor White', 'SP-Star', 57, 'Regular', 'POM', 'Nylon', 'Nylon', TRUE, 7.5),
('Marble Soda', 'SP-Star', 63.5, 'Regular', 'POM', 'Polycarbonate', 'Polycarbonate', TRUE, 7),
('TKC TANGERINE', 'C3', 62, 'Regular', 'POM', 'UHMWPE', 'UHMWPE', TRUE, 7),
('Aurora Series', 'WS', 63.5, 'Regular', 'POM', 'Polycarbonate', 'Nylon', TRUE, 8),
('Raeds', 'AEBoards', 63.5, 'Long', 'POM', 'Nylon', 'Nylon', TRUE, 7.5),
('Blaeck', 'AEBoards', 63.5, 'Regular', 'POM', 'Nylon', 'Nylon', TRUE, 7.5),
('Milk', 'Infinity Key', 63.5, 'Long', 'UHMWPE', 'UHMWPE', 'UHMWPE', TRUE, 7),
('CK Pastel Sky', 'Haimu', 63.5, 'Regular', 'POM', 'POM', 'Nylon', TRUE, 6.5),
('Blush', 'Aflion', 58, 'Long', 'POM', 'Polycarbonate', 'Nylon', TRUE, 6.5),
('Aqua King', 'Everglide', 62, 'Regular', 'Polycarbonate', 'Polycarbonate', 'Polycarbonate', TRUE, 8),
('Cherry Blossom', 'Durock', 65, 'Regular', 'P3', 'POM', 'POM', TRUE, 6),
('RedBlue', 'SP-Star', 57, 'Regular', 'POM', 'Polycarbonate', 'Polycarbonate', TRUE, 6.5),
('Robin', 'Gateron', 62, 'Regular', 'POM', 'Polycarbonate', 'PA66', TRUE, 5);

CREATE TABLE keyboards (
    keyboard_id SERIAL PRIMARY KEY,
    keyboard_name VARCHAR(30),
    brand VARCHAR(30),
    keyboard_size INTEGER,
    plate VARCHAR(20),
    weight_material VARCHAR(30)
);

INSERT INTO keyboards (keyboard_name, brand, keyboard_size, plate, weight_material) VALUES
('Neko SE', 'MONOKEI x SingaKBD', 40, 'Copper', 'Sandblasted Copper'),
('S46', 'SAM', 40, 'POM', 'Mirror PVD Stainless Steel'),
('Derivative R1', 'JJWKB', 60, 'Aluminum', 'Stainless Steel'),
('Sangeo65', 'Monstargear', 65, 'Aluminum', 'Mirror PVD Brass'),
('Jules', 'Zambumon', 65, 'POM', 'Aluminum'),
('Link65', 'OwLab', 65, 'Polycarbonate', 'Sandblasted Stainless Steel'),
('Bear65 V2', 'Jacky', 65, 'Polycarbonate', 'Coated Brass'),
('Aurora Input Series 65', 'Oblotzky', 65, 'FR4', 'Beadblasted Stainless Steel'),
('The Enjoy', 'TastyKeys', 65, 'POM', 'Coated Sandblasted Copper'),
('Leaf65', 'Fox Lab', 65, 'Polycarbonate', 'Mirror PVD Brass'),
('Harbour', 'Kibou', 65, 'Aluminum', 'Sandblasted Stainless Steel'),
('Zenith', 'Ion', 70, 'Aluminum', 'Beadblasted Brass'),
('Jelly Epoch', 'OwLab', 75, 'Polycarbonate', 'Coated Brass'),
('GHS.JE', 'Gone Hacking Studio', 75, 'Aluminum', 'Sandblasted Brass'),
('Sonnet', 'Mode', 75, 'POM', 'Coated Sandblasted Copper'),
('Ahgase', 'PolyWorks', 80, 'Aluminum', 'Sandblasted Stainless Steel');